Personal:
  $FIRST$: Alec
  $LAST$: Bonham
  $TITLE$: Statistics M.S.
  $BIO$: I am a recent graduate with a Statistics M.S. at University of Virginia  
  $LINKEDIN$: https://www.linkedin.com/
  $EMAIL$: john@doe.com
Projects:
  - $TITLE$: Project 1
    $URL$: http://www.zombo.com/
    $ICON$: pencil
    $BLURB$:  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc porta purus ac lorem posuere, in aliquet magna feugiat.
  - $TITLE$: Project 2
    $URL$: http://www.zombo.com/
    $ICON$: pencil
    $BLURB$: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc porta purus ac lorem posuere, in aliquet magna feugiat.
